set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR generic)

set(TOOLCHAIN_PREFIX $ENV{CROSS_COMPILE} CACHE FILEPATH "Toolchain prefix")
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)