#ifndef __LOCAL_CTRL_H__
#define __LOCAL_CTRL_H__

#include <reg_map.h>
#include <config.h>

#define SYS_MCU_LOCAL_CTRL_CTRL0		(SYS_MCU_LOCAL_CTRL_ADDR + 0x40)
#define SYS_MCU_LOCAL_CTRL_MSG0			(SYS_MCU_LOCAL_CTRL_ADDR + 0x50)
#define SYS_MCU_LOCAL_CTRL_MSG1			(SYS_MCU_LOCAL_CTRL_ADDR + 0x54)
#define SYS_MCU_LOCAL_CTRL_MSG2			(SYS_MCU_LOCAL_CTRL_ADDR + 0x58)
#define SYS_MCU_LOCAL_CTRL_MSG3			(SYS_MCU_LOCAL_CTRL_ADDR + 0x5c)
#define SYS_MCU_LOCAL_CTRL_NMI_ADDR		(SYS_MCU_LOCAL_CTRL_ADDR + 0x64)

#define SYS_MCU_LOCAL_CTRL_DOORBELL_TO_MCU	(SYS_MCU_LOCAL_CTRL_ADDR + 0x68)
#define SYS_MCU_LOCAL_CTRL_DOORBELL_TO_SOC	(SYS_MCU_LOCAL_CTRL_ADDR + 0x6c)

#define SYS_MCU_CPU_BOOT_ADDR			(SYS_MCU_LOCAL_CTRL_ADDR + 0x60)

#define CLCI_MCU_LOCAL_CTRL_CTRL0		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x40)
#define CLCI_MCU_LOCAL_CTRL_MSG0		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x50)
#define CLCI_MCU_LOCAL_CTRL_MSG1		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x54)
#define CLCI_MCU_LOCAL_CTRL_MSG2		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x58)
#define CLCI_MCU_LOCAL_CTRL_MSG3		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x5c)
#define CLCI_MCU_LOCAL_CTRL_NMI_ADDR		(CLCI_MCU_LOCAL_CTRL_ADDR + 0x64)

#define CLCI_MCU_LOCAL_CTRL_DOORBELL_TO_MCU	(CLCI_MCU_LOCAL_CTRL_ADDR + 0x68)
#define CLCI_MCU_LOCAL_CTRL_DOORBELL_TO_SOC	(CLCI_MCU_LOCAL_CTRL_ADDR + 0x6c)

#define CLCI_MCU_CPU_BOOT_ADDR			(CLCI_MCU_LOCAL_CTRL_ADDR + 0x60)

#define BIT_CPU_SOFT_RSTN			(1)
#define BIT_CPU_RUN_REQ				(1 << 1)
#define BIT_CPU_HALT_REG			(1 << 2)
#define BIT_BIU_RSTN				(1 << 3)
#define BIT_WDT_RSTN				(1 << 4)
#define BIT_TEST_NMI				(1 << 8)
#define BIT_TEST_SOFT_INT			(1 << 9)

#endif
